### ISSUE TITLE
The OEO viewer is not working

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeo-viewer#4]
See screenshot:

![grafik](https://github.com/OpenEnergyPlatform/oeo-viewer/assets/36884905/d5957d32-069f-4f66-9f49-6729bf5c638a)
https://openenergy-platform.org/viewer/oeo/

Tested in following conditions, all with the same results:
* Win 10, Firefox 102.12.0esr
* Win 10, Microsoft Edge 
* Android, Firefox 114.1.1
* Android, Chrome 114.0.575.131

**Comment by stap-m** [comment]
@MGlauer resolved it.
